name: Deploy File Upload Service

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy Function
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Setup Cloud SDK
              uses: google-github-actions/setup-gcloud@v2
              with:
                  project_id: ${{ secrets.GCP_PROJECT_ID }}
                  service_account_key: ${{ secrets.GCP_SA_KEY }}
                  export_default_credentials: true

            - name: Deploy to Google Cloud Functions
              working-directory: file-upload
              run: |
                  gcloud functions deploy HelloWorld \
                    --entry-point HelloWorld \
                    --runtime go116 \
                    --trigger-http \
                    --allow-unauthenticated
