name: Deploy File Upload Service

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy Function
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Set up Google Cloud authentication
              uses: google-github-actions/auth@v2
              with:
                  credentials_json: ${{ secrets.GCP_SA_KEY }}

            - name: Setup Cloud SDK
              uses: google-github-actions/setup-gcloud@v2
              with:
                  project_id: ${{ secrets.GCP_PROJECT_ID }}
                  export_default_credentials: true

            - name: Enable Cloud Resource Manager API
              run: |
                  gcloud services enable cloudresourcemanager.googleapis.com
            - name: Enable Cloud Run API
              run: |
                  gcloud services enable run.googleapis.com

            - name: Create fitus-file-bucket SA KEY
              working-directory: file-upload
              run: |
                  echo "${{ secrets.GCP_SA_KEY }}" > fitus-file-bucket.json
            - name: Deploy to Google Cloud Functions
              working-directory: file-upload
              run: |
                  gcloud functions deploy Upload \
                    --entry-point FileUpload \
                    --runtime go123 \
                    --trigger-http \
                    --allow-unauthenticated \
                    --gen2
